#!/bin/sh

FILES=$(git diff --cached --name-only --diff-filter=ACMR | sed 's| |\\ |g')
[ -z "$FILES" ] && exit 0

npx mega-linter-runner --remove-container --fix --filesonly $FILES

echo "$FILES" | xargs git add

exit 0
