#!/bin/sh

FILES=$(git diff --cached --name-only --diff-filter=ACMR | sed 's| |\\ |g')
[ -z "$FILES" ] && exit 0

if npx mega-linter-runner --remove-container --fix --filesonly $FILES; then
    echo "$FILES" | xargs git add
    exit 0
fi

exit 1
